# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiniProject02' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON'
pod 'GoogleMaps'
pod 'SWXMLHash', '~> 3.0.0'
  # Pods for MiniProject02

end
