# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleFBSignInUsingFirebase' do
 
	pod ‘Firebase’
	pod 'Firebase/Core'
	pod 'Firebase/Auth’

end
