# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MiniProject01' do

pod 'AFNetworking', '~> 3.0'
pod 'GoogleMaps'

end
